//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Utilities/Input/PlayerControlls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControlls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControlls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControlls"",
    ""maps"": [
        {
            ""name"": ""Main"",
            ""id"": ""854e3262-6774-4c52-bc30-14829d2c63c2"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""1659642f-a2cf-46e0-a8af-c3eee439ed83"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Action"",
                    ""type"": ""Button"",
                    ""id"": ""28db5d5e-310f-48b7-a783-7f74fba742ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AltAction"",
                    ""type"": ""Button"",
                    ""id"": ""a593f2d0-3ffe-49da-8362-208c7179a51c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""c0d3e7a4-3f24-4273-b1e5-aa2b798e8901"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""c22d2451-9970-4500-82fb-f1e6c299739c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""736541b6-2a9b-4985-9355-133e905efd24"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""9c9a9192-ad8d-45eb-8c0c-2365d27823b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""d56742e4-42bb-4d70-be1f-747501179929"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Mouse"",
                    ""type"": ""Value"",
                    ""id"": ""09f90b7c-a1ec-45e2-b24f-75e32672bac4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FirstSkill"",
                    ""type"": ""Button"",
                    ""id"": ""10c06492-1fbe-4c50-a33d-c21531f04b08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondSkill"",
                    ""type"": ""Button"",
                    ""id"": ""a4b88f37-75a7-4ef8-b6df-df4e2a5770c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThirdSkill"",
                    ""type"": ""Button"",
                    ""id"": ""c3590c2b-1990-49c7-ad5f-8c292e4cb41f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FourthSkill"",
                    ""type"": ""Button"",
                    ""id"": ""d4577a8f-25c7-4370-87e1-1c0548d96dbc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FifthSkill"",
                    ""type"": ""Button"",
                    ""id"": ""fa7f793e-0abc-4fdc-8de2-98ee1c634b12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""1aa5b78f-8db6-4234-8530-8bc3cdb031d2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c63447b7-1e66-472d-9cee-e7499e76bb9e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f6e99796-ee28-4b2a-bf97-0153a180620c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""761acbbb-18d3-4486-be53-d6ad650a755a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""11d49d27-6b39-4625-a7de-b89529fc3517"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e1d65454-882e-4210-a0f4-451082ced1cf"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41b0cb3f-12d0-4faa-98de-0a4ed2d96232"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AltAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2983ba49-cf9c-4bb7-b073-c9419cc431d5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a94a3e4-100d-41a6-afae-1b638d36939e"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7ce045a-afd4-4811-9b63-16918753e232"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72d28d78-a585-4ea3-a53a-b165826d2ded"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b7f7396-ae11-4e90-8f46-5f45bd04dfba"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8222757-c277-44d8-a4e8-e26104d45398"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""863762c1-8352-40d3-9a46-9130507dd3ef"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f52ff8e-fb96-403b-b5ad-4cd80c55ffe0"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70cddbb8-62a8-48a1-ad12-05aaa6f75cbf"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThirdSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c5d7a4c-53cd-426d-b274-74818d0a948e"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FourthSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf0aef4c-d5d5-4ed4-bffb-e69c8b821c5a"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FifthSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Main
        m_Main = asset.FindActionMap("Main", throwIfNotFound: true);
        m_Main_Movement = m_Main.FindAction("Movement", throwIfNotFound: true);
        m_Main_Action = m_Main.FindAction("Action", throwIfNotFound: true);
        m_Main_AltAction = m_Main.FindAction("AltAction", throwIfNotFound: true);
        m_Main_Jump = m_Main.FindAction("Jump", throwIfNotFound: true);
        m_Main_Inventory = m_Main.FindAction("Inventory", throwIfNotFound: true);
        m_Main_Interaction = m_Main.FindAction("Interaction", throwIfNotFound: true);
        m_Main_PauseMenu = m_Main.FindAction("PauseMenu", throwIfNotFound: true);
        m_Main_Look = m_Main.FindAction("Look", throwIfNotFound: true);
        m_Main_Mouse = m_Main.FindAction("Mouse", throwIfNotFound: true);
        m_Main_FirstSkill = m_Main.FindAction("FirstSkill", throwIfNotFound: true);
        m_Main_SecondSkill = m_Main.FindAction("SecondSkill", throwIfNotFound: true);
        m_Main_ThirdSkill = m_Main.FindAction("ThirdSkill", throwIfNotFound: true);
        m_Main_FourthSkill = m_Main.FindAction("FourthSkill", throwIfNotFound: true);
        m_Main_FifthSkill = m_Main.FindAction("FifthSkill", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Main
    private readonly InputActionMap m_Main;
    private IMainActions m_MainActionsCallbackInterface;
    private readonly InputAction m_Main_Movement;
    private readonly InputAction m_Main_Action;
    private readonly InputAction m_Main_AltAction;
    private readonly InputAction m_Main_Jump;
    private readonly InputAction m_Main_Inventory;
    private readonly InputAction m_Main_Interaction;
    private readonly InputAction m_Main_PauseMenu;
    private readonly InputAction m_Main_Look;
    private readonly InputAction m_Main_Mouse;
    private readonly InputAction m_Main_FirstSkill;
    private readonly InputAction m_Main_SecondSkill;
    private readonly InputAction m_Main_ThirdSkill;
    private readonly InputAction m_Main_FourthSkill;
    private readonly InputAction m_Main_FifthSkill;
    public struct MainActions
    {
        private @PlayerControlls m_Wrapper;
        public MainActions(@PlayerControlls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Main_Movement;
        public InputAction @Action => m_Wrapper.m_Main_Action;
        public InputAction @AltAction => m_Wrapper.m_Main_AltAction;
        public InputAction @Jump => m_Wrapper.m_Main_Jump;
        public InputAction @Inventory => m_Wrapper.m_Main_Inventory;
        public InputAction @Interaction => m_Wrapper.m_Main_Interaction;
        public InputAction @PauseMenu => m_Wrapper.m_Main_PauseMenu;
        public InputAction @Look => m_Wrapper.m_Main_Look;
        public InputAction @Mouse => m_Wrapper.m_Main_Mouse;
        public InputAction @FirstSkill => m_Wrapper.m_Main_FirstSkill;
        public InputAction @SecondSkill => m_Wrapper.m_Main_SecondSkill;
        public InputAction @ThirdSkill => m_Wrapper.m_Main_ThirdSkill;
        public InputAction @FourthSkill => m_Wrapper.m_Main_FourthSkill;
        public InputAction @FifthSkill => m_Wrapper.m_Main_FifthSkill;
        public InputActionMap Get() { return m_Wrapper.m_Main; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainActions set) { return set.Get(); }
        public void SetCallbacks(IMainActions instance)
        {
            if (m_Wrapper.m_MainActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_MainActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnMovement;
                @Action.started -= m_Wrapper.m_MainActionsCallbackInterface.OnAction;
                @Action.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnAction;
                @Action.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnAction;
                @AltAction.started -= m_Wrapper.m_MainActionsCallbackInterface.OnAltAction;
                @AltAction.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnAltAction;
                @AltAction.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnAltAction;
                @Jump.started -= m_Wrapper.m_MainActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnJump;
                @Inventory.started -= m_Wrapper.m_MainActionsCallbackInterface.OnInventory;
                @Inventory.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnInventory;
                @Inventory.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnInventory;
                @Interaction.started -= m_Wrapper.m_MainActionsCallbackInterface.OnInteraction;
                @Interaction.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnInteraction;
                @Interaction.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnInteraction;
                @PauseMenu.started -= m_Wrapper.m_MainActionsCallbackInterface.OnPauseMenu;
                @PauseMenu.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnPauseMenu;
                @PauseMenu.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnPauseMenu;
                @Look.started -= m_Wrapper.m_MainActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnLook;
                @Mouse.started -= m_Wrapper.m_MainActionsCallbackInterface.OnMouse;
                @Mouse.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnMouse;
                @Mouse.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnMouse;
                @FirstSkill.started -= m_Wrapper.m_MainActionsCallbackInterface.OnFirstSkill;
                @FirstSkill.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnFirstSkill;
                @FirstSkill.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnFirstSkill;
                @SecondSkill.started -= m_Wrapper.m_MainActionsCallbackInterface.OnSecondSkill;
                @SecondSkill.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnSecondSkill;
                @SecondSkill.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnSecondSkill;
                @ThirdSkill.started -= m_Wrapper.m_MainActionsCallbackInterface.OnThirdSkill;
                @ThirdSkill.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnThirdSkill;
                @ThirdSkill.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnThirdSkill;
                @FourthSkill.started -= m_Wrapper.m_MainActionsCallbackInterface.OnFourthSkill;
                @FourthSkill.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnFourthSkill;
                @FourthSkill.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnFourthSkill;
                @FifthSkill.started -= m_Wrapper.m_MainActionsCallbackInterface.OnFifthSkill;
                @FifthSkill.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnFifthSkill;
                @FifthSkill.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnFifthSkill;
            }
            m_Wrapper.m_MainActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Action.started += instance.OnAction;
                @Action.performed += instance.OnAction;
                @Action.canceled += instance.OnAction;
                @AltAction.started += instance.OnAltAction;
                @AltAction.performed += instance.OnAltAction;
                @AltAction.canceled += instance.OnAltAction;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Inventory.started += instance.OnInventory;
                @Inventory.performed += instance.OnInventory;
                @Inventory.canceled += instance.OnInventory;
                @Interaction.started += instance.OnInteraction;
                @Interaction.performed += instance.OnInteraction;
                @Interaction.canceled += instance.OnInteraction;
                @PauseMenu.started += instance.OnPauseMenu;
                @PauseMenu.performed += instance.OnPauseMenu;
                @PauseMenu.canceled += instance.OnPauseMenu;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Mouse.started += instance.OnMouse;
                @Mouse.performed += instance.OnMouse;
                @Mouse.canceled += instance.OnMouse;
                @FirstSkill.started += instance.OnFirstSkill;
                @FirstSkill.performed += instance.OnFirstSkill;
                @FirstSkill.canceled += instance.OnFirstSkill;
                @SecondSkill.started += instance.OnSecondSkill;
                @SecondSkill.performed += instance.OnSecondSkill;
                @SecondSkill.canceled += instance.OnSecondSkill;
                @ThirdSkill.started += instance.OnThirdSkill;
                @ThirdSkill.performed += instance.OnThirdSkill;
                @ThirdSkill.canceled += instance.OnThirdSkill;
                @FourthSkill.started += instance.OnFourthSkill;
                @FourthSkill.performed += instance.OnFourthSkill;
                @FourthSkill.canceled += instance.OnFourthSkill;
                @FifthSkill.started += instance.OnFifthSkill;
                @FifthSkill.performed += instance.OnFifthSkill;
                @FifthSkill.canceled += instance.OnFifthSkill;
            }
        }
    }
    public MainActions @Main => new MainActions(this);
    public interface IMainActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnAction(InputAction.CallbackContext context);
        void OnAltAction(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnPauseMenu(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnMouse(InputAction.CallbackContext context);
        void OnFirstSkill(InputAction.CallbackContext context);
        void OnSecondSkill(InputAction.CallbackContext context);
        void OnThirdSkill(InputAction.CallbackContext context);
        void OnFourthSkill(InputAction.CallbackContext context);
        void OnFifthSkill(InputAction.CallbackContext context);
    }
}
